"use client";

import { config } from "@repo/config";
import { orpc } from "@shared/lib/orpc-query-utils";
import { useQuery } from "@tanstack/react-query";
import { Alert, AlertDescription } from "@ui/components/alert";
import { Button } from "@ui/components/button";
import {
	Card,
	CardContent,
	CardDescription,
	CardHeader,
	CardTitle,
} from "@ui/components/card";
import { AlertCircle, ExternalLink, FileText, Loader2 } from "lucide-react";
import Link from "next/link";
import {
	type NewsAnalysisOutput,
	NewsAnalyzerResults,
} from "../../../../../components/tools/news-analyzer/news-analyzer-results";

interface SharedNewsAnalysisProps {
	analysisId: string;
}

export function SharedNewsAnalysis({ analysisId }: SharedNewsAnalysisProps) {
	const { data, isLoading, error } = useQuery({
		...orpc.share.getNewsAnalysis.queryOptions({
			input: { analysisId },
		}),
	});

	if (isLoading) {
		return (
			<div className="container mx-auto max-w-4xl px-4 py-8">
				<Card className="p-8">
					<div className="flex items-center justify-center">
						<Loader2 className="mr-2 size-6 animate-spin text-primary" />
						<span>Loading analysis...</span>
					</div>
				</Card>
			</div>
		);
	}

	if (error || !data?.analysis) {
		return (
			<div className="container mx-auto max-w-4xl px-4 py-8">
				<Card className="p-8">
					<Alert variant="error">
						<AlertCircle className="h-4 w-4" />
						<AlertDescription>
							{error instanceof Error
								? error.message
								: "This analysis could not be found. It may have been deleted."}
						</AlertDescription>
					</Alert>
					<div className="mt-6 flex flex-col items-center gap-4">
						<p className="text-sm text-muted-foreground">
							Want to analyze your own news articles?
						</p>
						<Button asChild>
							<Link href="/auth/login?redirect=/app/tools/news-analyzer">
								Try {config.appName}
							</Link>
						</Button>
					</div>
				</Card>
			</div>
		);
	}

	const { analysis } = data;
	const articleSource = analysis.sourceUrl ?? analysis.sourceText;
	const isUrl = !!analysis.sourceUrl;

	return (
		<div className="container mx-auto max-w-4xl px-4 py-8">
			<div className="space-y-6">
				{/* Header */}
				<div className="text-center">
					<h1 className="text-3xl font-bold tracking-tight">
						{analysis.title ?? "News Analysis"}
					</h1>
					<p className="mt-2 text-muted-foreground">
						Analyzed on{" "}
						{new Date(analysis.createdAt).toLocaleDateString(
							undefined,
							{
								weekday: "long",
								year: "numeric",
								month: "long",
								day: "numeric",
							},
						)}
						{analysis.createdBy && ` by ${analysis.createdBy}`}
					</p>
				</div>

				{/* Source Card */}
				<Card>
					<CardHeader>
						<CardTitle>Source</CardTitle>
						<CardDescription>
							The original article that was analyzed
						</CardDescription>
					</CardHeader>
					<CardContent>
						<div className="flex items-start gap-2">
							{isUrl ? (
								<>
									<ExternalLink className="size-4 text-muted-foreground flex-shrink-0 mt-0.5" />
									<a
										href={analysis.sourceUrl ?? "#"}
										target="_blank"
										rel="noopener noreferrer"
										className="text-sm text-primary hover:underline break-all"
									>
										{analysis.sourceUrl}
									</a>
								</>
							) : (
								<>
									<FileText className="size-4 text-muted-foreground flex-shrink-0 mt-0.5" />
									<p className="text-sm text-muted-foreground">
										{articleSource &&
										articleSource.length > 300
											? articleSource.slice(0, 300) +
												"..."
											: articleSource}
									</p>
								</>
							)}
						</div>
					</CardContent>
				</Card>

				{/* Analysis Results */}
				<NewsAnalyzerResults
					output={analysis.analysis as unknown as NewsAnalysisOutput}
				/>

				{/* CTA Section */}
				<Card className="border-primary/20 bg-primary/5">
					<CardContent className="pt-6">
						<div className="flex flex-col items-center text-center gap-4">
							<div>
								<h2 className="text-xl font-semibold">
									Want to analyze your own articles?
								</h2>
								<p className="mt-1 text-muted-foreground">
									{config.appName} helps you understand news
									bias, sentiment, and key facts with
									AI-powered analysis.
								</p>
							</div>
							<Button size="lg" asChild>
								<Link href="/auth/login?redirect=/app/tools/news-analyzer">
									Try it yourself
								</Link>
							</Button>
						</div>
					</CardContent>
				</Card>

				{/* Footer Branding */}
				<div className="border-t pt-6 text-center">
					<p className="text-sm text-muted-foreground">
						Generated by{" "}
						<Link
							href="/"
							className="font-medium text-primary hover:underline"
						>
							{config.appName}
						</Link>
					</p>
				</div>
			</div>
		</div>
	);
}
