import { createLocalStorageProvider } from "@repo/storage";
import { NextResponse } from "next/server";

/**
 * API route for handling local storage downloads.
 * This endpoint serves files via signed URLs generated by LocalStorageProvider.
 *
 * **IMPORTANT: This route is for development only.**
 *
 * Query parameters (from signed URL):
 * - bucket: The storage bucket name
 * - key: The file key/path
 * - expires: Unix timestamp (ms) when the URL expires
 * - token: HMAC signature for verification
 */
export async function GET(request: Request): Promise<Response> {
	// Only allow in development
	if (process.env.NODE_ENV === "production") {
		return NextResponse.json(
			{ error: "Local storage is not available in production" },
			{ status: 403 },
		);
	}

	const url = new URL(request.url);
	const bucket = url.searchParams.get("bucket");
	const key = url.searchParams.get("key");
	const expires = url.searchParams.get("expires");
	const token = url.searchParams.get("token");

	// Validate required parameters
	if (!bucket || !key || !expires || !token) {
		return NextResponse.json(
			{ error: "Missing required parameters" },
			{ status: 400 },
		);
	}

	const expiresAt = Number.parseInt(expires, 10);
	if (Number.isNaN(expiresAt)) {
		return NextResponse.json(
			{ error: "Invalid expires parameter" },
			{ status: 400 },
		);
	}

	// Verify the signed URL token
	const provider = createLocalStorageProvider();
	const isValid = provider.verifyToken(
		bucket,
		key,
		expiresAt,
		"download",
		token,
	);

	if (!isValid) {
		return NextResponse.json(
			{ error: "Invalid or expired download URL" },
			{ status: 403 },
		);
	}

	try {
		// Read the file from local storage
		const { data, contentType } = await provider.readFile(key, bucket);

		// Convert Buffer to Uint8Array for NextResponse compatibility
		return new NextResponse(new Uint8Array(data), {
			status: 200,
			headers: {
				"Content-Type": contentType,
				"Content-Length": data.byteLength.toString(),
				"Cache-Control": "private, max-age=3600",
			},
		});
	} catch (error) {
		console.error("Local storage download error:", error);
		return NextResponse.json({ error: "File not found" }, { status: 404 });
	}
}

/**
 * OPTIONS handler for CORS preflight requests.
 */
export async function OPTIONS(): Promise<Response> {
	return new NextResponse(null, {
		status: 204,
		headers: {
			"Access-Control-Allow-Origin": "*",
			"Access-Control-Allow-Methods": "GET, OPTIONS",
			"Access-Control-Allow-Headers": "Content-Type",
			"Access-Control-Max-Age": "86400",
		},
	});
}
