import { createLocalStorageProvider } from "@repo/storage";
import { NextResponse } from "next/server";

/**
 * API route for handling local storage uploads.
 * This endpoint receives files uploaded via signed URLs generated by LocalStorageProvider.
 *
 * **IMPORTANT: This route is for development only.**
 *
 * Query parameters (from signed URL):
 * - bucket: The storage bucket name
 * - key: The file key/path
 * - expires: Unix timestamp (ms) when the URL expires
 * - token: HMAC signature for verification
 * - contentType: Expected content type of the upload
 */
export async function PUT(request: Request): Promise<Response> {
	// Only allow in development
	if (process.env.NODE_ENV === "production") {
		return NextResponse.json(
			{ error: "Local storage is not available in production" },
			{ status: 403 },
		);
	}

	const url = new URL(request.url);
	const bucket = url.searchParams.get("bucket");
	const key = url.searchParams.get("key");
	const expires = url.searchParams.get("expires");
	const token = url.searchParams.get("token");
	const contentType =
		url.searchParams.get("contentType") ?? "application/octet-stream";

	// Validate required parameters
	if (!bucket || !key || !expires || !token) {
		return NextResponse.json(
			{ error: "Missing required parameters" },
			{ status: 400 },
		);
	}

	const expiresAt = Number.parseInt(expires, 10);
	if (Number.isNaN(expiresAt)) {
		return NextResponse.json(
			{ error: "Invalid expires parameter" },
			{ status: 400 },
		);
	}

	// Verify the signed URL token
	const provider = createLocalStorageProvider();
	const isValid = provider.verifyToken(bucket, key, expiresAt, "upload", token);

	if (!isValid) {
		return NextResponse.json(
			{ error: "Invalid or expired upload URL" },
			{ status: 403 },
		);
	}

	// Read the request body
	const body = await request.arrayBuffer();
	if (body.byteLength === 0) {
		return NextResponse.json({ error: "Empty file body" }, { status: 400 });
	}

	try {
		// Write the file to local storage
		await provider.writeFile(key, bucket, Buffer.from(body), contentType);

		return NextResponse.json(
			{
				success: true,
				key,
				bucket,
				size: body.byteLength,
			},
			{ status: 200 },
		);
	} catch (error) {
		console.error("Local storage upload error:", error);
		return NextResponse.json(
			{ error: "Failed to save file" },
			{ status: 500 },
		);
	}
}

/**
 * OPTIONS handler for CORS preflight requests.
 */
export async function OPTIONS(): Promise<Response> {
	return new NextResponse(null, {
		status: 204,
		headers: {
			"Access-Control-Allow-Origin": "*",
			"Access-Control-Allow-Methods": "PUT, OPTIONS",
			"Access-Control-Allow-Headers": "Content-Type",
			"Access-Control-Max-Age": "86400",
		},
	});
}
